name: Go
on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: build
        run: go build -v ./...

      - name: vet
        run: go vet -v ./...

      - name: staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck -checks all ./...

      - name: test
        run: go test -v ./...

