name: Go

on:
  push:
    branches: [ "amogus" ]
  pull_request:
    branches: [ "amogus" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet -v ./...

    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2023.1.7"

    - name: Test
      run: go test -v ./...

